services:
  mongo:
    image: mongo:8.0.15-noble
    container_name: mongo-word-db
    command: ["--auth"]
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    networks:
      - app_network
    volumes:
      - mongo-impostor:/data/db
      - mongo-impostor-config:/data/configdb
      - ./scripts/mongo:/docker-entrypoint-initdb.d
  

volumes:
  mongo-impostor:
  mongo-impostor-config:
networks:
  app_network: